export default {
  SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
  SET_CURRENCY: "SET_CURRENCY",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  SET_CATEGORY_FILTER: "SET_CATEGORY_FILTER",
  TOGGLE_MODAL: "TOGGLE_MODAL",
};
